data:
    dataset: 'my_dataset'  # <--- CHANGED: Use snake_case here
    root: 'datasets/sim_dataset'
    export_folder: 'val'
    preprocessing:
        resize: [360, 640] 
    gaussian_label:
        enable: false
        sigma: 1.
    augmentation:
        photometric:
            enable: false
    homography_adaptation:
        enable: true
        num: 100
        aggregation: 'sum'
        filter_counts: 0
        homographies:
            params:
                translation: true
                rotation: true
                scaling: true
                perspective: true
                scaling_amplitude: 0.2
                perspective_amplitude_x: 0.2
                perspective_amplitude_y: 0.2
                allow_artifacts: true
                patch_ratio: 0.85

training:
    workers_test: 2

front_end_model: 'Val_model_heatmap'  # <--- Make sure this line exists and is NOT indented

model:
    name: 'SuperPointNet'
    params: {
    }    
    batch_size: 1
    eval_batch_size: 1
    detection_threshold: 0.015
    nn_thresh: 1.0 # 0.7
    nms: 4
    top_k: 600
    subpixel:
        enable: true
        patch_size: 5

    pretrained: 'pretrained/superpoint_v1_compatible.pth.tar'